version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    restart: unless-stopped
    depends_on:
      - backend
